# Generated by Django 3.1.7 on 2021-04-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('Product_quality', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=500)),
                ('rating', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=500)),
                ('publish_date', models.DateField()),
                ('Product_prize', models.IntegerField()),
                ('category', models.CharField(default='', max_length=50)),
                ('sub_category', models.CharField(default='', max_length=50)),
                ('photo', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
